language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
